apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-chatroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-chatroom
  template:
    metadata:
      labels:
        app: ms-chatroom
    spec:
      containers:
        - image: rsobook/ms-chatroom:2.0.0
          name: ms-chatroom
          env:
            - name: PORT
              value: '80'
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://ms-etcd:2379
          ports:
          - containerPort: 80
            protocol: TCP